services:
  wallet-db:
    image: postgres:15-alpine
    container_name: wallet-db
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5
